### ISSUE TITLE
Move kind-projector to typelevel

### ISSUE THREAD

**Issue by non** [typelevel/kind-projector#100]
Awhile ago I was contacted by @milessabin on behalf of the Scala SIP committee. There's been a desire to create a smooth upgrade path from Scala 2 to Dotty (with and without kind-projector) and they foresaw wanting to help do work.

In light of this I'm planning to move _kind-projector_ to publish under `org.typelevel` so that a larger pool of people will be able to make releases. As part of that I'd also move the organization from `non` to `typelevel` and add a link to the Scala CoC as per Typelevel rules.

@TomasMikula and @SethTisue do either of you have any concerns about this? I'm planning to do this in the next few days but I realized I should check in with you both first. Feel free to 👍 this issue or respond with any concerns you have.

(And continuing thanks for helping maintain kind-projector!)

**Comment by SethTisue** [comment]
SGTM, no concerns

**Comment by TomasMikula** [comment]
Unless it was added to the list of typelevel projects (on typelevel.org) by accident, kind-projector has been a typelevel project as long as I remember. In that light, the move is just a technicality. No concerns with that.

**Comment by non** [comment]
Great, thanks everyone! 👍

**Comment by milessabin** [comment]
Awesome! Thanks :-)

Also, i'm happy to volunteer as an additional maintainer if you need one.

**Comment by non** [comment]
Project moved and @milessabin added.

I'm going to change the organization to `org.typelevel` now and release 0.10.0 with the new organization.

**Comment by non** [comment]
Closing this issue. At this point the README is updated to 0.10.0, seems like our integrations are all still working, and we've shifted over. Thanks everyone!
