### ISSUE TITLE
Document the use of `*` as a placeholder and deprecate the use of `?`

### ISSUE THREAD

**Issue by smarter** [typelevel/kind-projector#108]
In https://github.com/typelevel/kind-projector/pull/91 `*` was introduced as an alternative placeholder syntax, as part of a long-term plan for repurposing `?` for wildcards in Scala (see http://dotty.epfl.ch/docs/reference/changed-features/wildcards.html). To allow cross-compilation, we recently added `-Ykind-projector` to Dotty to support the `*` placeholder. However, the documentation of kind-projector does not mention this new syntax, and the old one isn't deprecated, so people are unlikely to start using it. Could this be fixed ?

/cc @milessabin

**Comment by LukaJCB** [comment]
I can go through cats and change all of the use cases there soonish.

**Comment by milessabin** [comment]
I'll PR a doc change ASAP.

**Comment by dwijnand** [comment]
And a runtime deprecation warning, right?  (Ideally logging only once per compilation unit, rather for each instance.)

**Comment by gabro** [comment]
I would also suggest a scalafix rule that could be applied by scala steward once the old syntax gets removed

**Comment by VladKopanev** [comment]
I have added an issue for IDEA scala pluggin to support new placeholder : https://youtrack.jetbrains.net/issue/SCL-15756

**Comment by milessabin** [comment]
PR with a simple switch from `?` to `*` in the docs and examples here: https://github.com/typelevel/kind-projector/pull/109.

There ought to be a more explanatory paragraph in the README, but I wasn't sure quite how to structure it: putting it right at the beginning is a bit disruptive for someone who just wants to learn about the plugin. OTOH there isn't really a particularly natural break to insert it later, and tacking it on right at the end makes it a bit hard to discover.

**Comment by sugakandrey** [comment]
@VladKopanev thanks for notification, I've added support for `*`-syntax to scala-plugin. It is only available in nightly builds right now, but it will be available in 2019.2 builds as well.
IntelliJ users can migrate to new syntax via `Run inspection by Name` action, choosing `Deprecated Identifier` inspection ![](https://i.imgur.com/R8SL6nR.png) and then invoking ```Replace with `*`-syntax``` quickfix. ![](https://i.imgur.com/60VaroD.png).

**Comment by jrduncans** [comment]
Any progress here? Kind of awkward now that IntelliJ has shipped with a warning that `?` is deprecated, but there's nothing on the kind-projector site about it.
