### ISSUE TITLE
Type synonyms don't work

### ISSUE THREAD

**Issue by koterpillar** [typelevel/kind-projector#129]
The first example in the README is:

```scala
type IntOrA[A] = Either[Int, A]
```

However, the kind projector doesn't actually help simplifying it to the expected:

```scala
type IntOrA = Either[Int, *]
```

Here is an Ammonite session:

```
@ import $plugin.$ivy.`org.typelevel:kind-projector_2.12.10:0.11.0`
import $plugin.$

@ type IntOrA = Either[Int, *]
cmd2.sc:1: type Λ$ takes type parameters
type IntOrA = Either[Int, *]
              ^
Compilation Failed
```

Alternatively, [Scastie link](https://scastie.scala-lang.org/02ROZHSjQ72DWkYhVhkGQA).

**Comment by TomasMikula** [comment]
Hi @koterpillar, that is not supposed to compile, for the same reason why

```scala
type MyList = List
```

does not compile:

```
type List takes type parameters
```

One could say that it is a limitation of the Scala language, but not of kind-projector.
