### ISSUE TITLE
Version `0.11.0` is not found in `https://repo1.maven.org/maven2/org/typelevel/kind-projector_2.13/`

### ISSUE THREAD

**Issue by UkonnRa** [typelevel/kind-projector#145]
Because version `0.11.0` is not found in `https://repo1.maven.org/maven2/org/typelevel/kind-projector_2.13/`, so `addCompilerPlugin("org.typelevel" %% "kind-projector" % "0.11.0")` with `scalaVersion := "2.13.1"` will fail.

![Screenshot](https://user-images.githubusercontent.com/16066720/78471759-4965cf80-7766-11ea-87e2-0c8f5278a626.png)

 Now a walkaround is `addCompilerPlugin("org.typelevel" % "kind-projector_2.13.1" % "0.11.0")`

**Comment by ritschwumm** [comment]
the readme now advises to use `addCompilerPlugin("org.typelevel" %% "kind-projector" % "0.11.0" cross CrossVersion.full)` - does that work?

**Comment by UkonnRa** [comment]
Cool, thanks!
