### ISSUE TITLE
Release for Scala 2.13.2

### ISSUE THREAD

**Issue by abdolence** [typelevel/kind-projector#148]
Scala 2.13.2 is now available and, since it is CrossVersion.full, it would be great to have the updated version for it as well.
(Just kindly reminder :)
Thanks

**Comment by abdolence** [comment]
Just found this, https://github.com/typelevel/kind-projector/pull/147
So, probably we're expecting it soon, thanks!

**Comment by larsrh** [comment]
Release running now ☺
