### ISSUE TITLE
Release for Scala 2.13.4 (coming soon)

### ISSUE THREAD

**Issue by SethTisue** [typelevel/kind-projector#166]
just a heads up that 2.13.4 may arrive on Maven Central as soon as Thursday, as per https://contributors.scala-lang.org/t/coming-soon-scala-2-13-4/4555/8, and people will be wanting a kind-projector build

**Comment by larsrh** [comment]
#167

**Comment by larsrh** [comment]
0.11.1 is out.

**Comment by mr-git** [comment]
congratulation with release!
when it will get published on maven? https://mvnrepository.com/artifact/org.typelevel/kind-projector - shows only 0.11.0 as latest :/

**Comment by larsrh** [comment]
I forgot to press "Release" on Sonatype :facepalm: I've done that now
