### ISSUE TITLE
Release for 2.13.4

### ISSUE THREAD

**Issue by Odomontois** [typelevel/kind-projector#168]

**Comment by larsrh** [comment]
This is already out: https://oss.sonatype.org/content/repositories/public/org/typelevel/kind-projector_2.13.4/

**Comment by Odomontois** [comment]
Thank you. Sorry for bothering

**Comment by larsrh** [comment]
No worries :slightly_smiling_face:

**Comment by nafg** [comment]
readme isn't updated
