### ISSUE TITLE
update to 0.11.1 caused a floating point arithmetic change

### ISSUE THREAD

**Issue by erikerlandson** [typelevel/kind-projector#169]
Since the update to kind-projector 0.11.1 some of my unit tests are flaking on floating point ops, it seems to be specifically in monoid property testing.  The differences seem to be at or near the unit of least precision (ULP), for example:
```
Falsified after 18 passed tests.
> Labels of failing property: 
Expected: Quantity(1.2979896686839215E124)
Received: Quantity(1.2979896686839217E124)
```
These deviations seem to be relatively uncommon. I can usually get my unit tests to pass by re-running them, but the behavior is new.

**Comment by SethTisue** [comment]
it seems far-fetched that this could actually be related to a kind-projector upgrade

**Comment by larsrh** [comment]
Indeed, this is highly unlikely.
