### ISSUE TITLE
Officially deprecate/remove the `?`-based syntax in favor of `*`

### ISSUE THREAD

**Issue by smarter** [typelevel/kind-projector#171]
According to the project README:

> ?, +?, and -? (deprecated syntax; same meaning as the above)

But as far as I can see the plugin doesn't emit any deprecation warning when using the old syntax. To make it safer for Scala to repurpose `?` (cf http://dotty.epfl.ch/docs/reference/changed-features/wildcards.html), it'd be great if we could ensure people have stopped using it with kind-projector, so a deprecation warning followed by a removal would be useful.

**Comment by larsrh** [comment]
Sounds good. Any takers?
