### ISSUE TITLE
Cannot upgrade from 0.10.3 to 0.11.3

### ISSUE THREAD

**Issue by lukaszlenart** [typelevel/kind-projector#179]
I want to upgrade Scala to 2.12.13 version but I'm blocked by this plugin. Right now we are using the below setup and it works with Scala 2.12.10

```
lazy val documentGeneration =
  (project in file("document-generation"))
    .settings(moduleName := "document-generation")
    .settings(commonSettings)
    .settings {
      libraryDependencies ++= {
        Seq(
          "com.softwaremill.quicklens" %% "quicklens" % "1.6.1",
          "org.apache.pdfbox"          % "pdfbox"     % "2.0.22",
          compilerPlugin("org.typelevel" %% "kind-projector" % "0.10.3"),
          "com.dimafeng" %% "testcontainers-scala-scalatest"  % testcontainersScalaV % Test,
          "com.dimafeng" %% "testcontainers-scala-postgresql" % testcontainersScalaV % Test
        )
      }
    }
    .dependsOn(...)
```

I tried apply
```
compilerPlugin("org.typelevel" %% "kind-projector" % "0.11.3"),
```
but then I got 
```
sbt.librarymanagement.ResolveException: Error downloading org.typelevel:kind-projector_2.12:0.11.3
```
so I used
```
compilerPlugin("org.typelevel" % "kind-projector_2.12.13" % "0.11.3"),
```
but got
```
Modules were resolved with conflicting cross-version suffixes in ProjectRef(uri("file:/.../.../commons/"), "documentGeneration"):
org.typelevel:kind-projector _2.12, _2.12.13
```

How can I upgrade the plugin?

**Comment by larsrh** [comment]
Hi Lukasz, unfortunately `compilerPlugin` does not use the full Scala version in the suffix, which is necessary for almost all compiler plugins. Try:

```
compilerPlugin("org.typelevel" %% "kind-projector" % "0.11.3" cross CrossVersion.full)
```

Also, make sure that this line is identical in all of your submodules.

**Comment by lukaszlenart** [comment]
Thanks, but that didn't work
```
Modules were resolved with conflicting cross-version suffixes in ProjectRef(uri("file:/..../..../commons/"), "documentGeneration"):
org.typelevel:kind-projector _2.12, _2.12.13
```

I do not compile this library for multiple Scala versions and I don't have `CrossVersion` defined.

I tried use it like this
```
.settings(addCompilerPlugin("org.typelevel" %% "kind-projector" % "0.11.3" cross CrossVersion.full))
```

but still the same.

**Comment by larsrh** [comment]
The error message suggests that you are depending on another project (`"file:/..../..../commons/"`) that also uses kind-projector, where you don't have the `cross CrossVersion.full` suffix for the dependency.

**Comment by lukaszlenart** [comment]
`documentGeneration` module is part of the commons project (multiple modules in one project) and `documentGeneration` is the only module that uses `kind-projector` plugin.

And I just removed some sensitive information from the class path and replaced them with `....`

**Comment by larsrh** [comment]
Is the source code available in some repository? Otherwise this is hard to debug. It seems that kind-projector is somehow in your transitive dependencies.

**Comment by lukaszlenart** [comment]
No, it's a private repo under NDA, so I cannot share too many details :( And yes, I think your point with transitive dependency can be the case, will try to investigate this path, thanks!

**Comment by larsrh** [comment]
This plugin might help in the investigation: https://github.com/sbt/sbt-dependency-graph

**Comment by lukaszlenart** [comment]
Hmm... I know this plugin but how can I use it to find compiler plugins?

**Comment by larsrh** [comment]
If kind-projector is transitively pulled in via a library, it might appear in the normal dependency tree.

**Comment by lukaszlenart** [comment]
So... it doesn't :(

**Comment by SethTisue** [comment]
I'm not sure what else to suggest except perhaps: progressively disable or remove parts of your build until the problem goes away, and then add things back one at a time.

I'm confident there is no kind-projector issue, per se, here. So I'm closing the ticket, but also happy to discuss further, especially if new information comes to light.

**Comment by lukaszlenart** [comment]
Looks like the simplest solution is to remove the code that depends on the kind-projector and then remove the plugin as well.

**Comment by lukaszlenart** [comment]
Ok, after some help from teammates we finally found the issue, it was another plugin that was using an older version of `kind-projector`. And instead using `sbt libraryDependencies` can help here.

**Comment by lukaszlenart** [comment]
I would like to say sorry if you were touched by [my comment](https://github.com/typelevel/kind-projector/issues/179#issuecomment-779630257) - it was a real pain in the ass and it blocked upgrading to Scala 2.12.13, and this plugin was used just because it was needed by one custom function to support Cats' Kleisli (which are gone now).
