### ISSUE TITLE
Release from CI

### ISSUE THREAD

**Issue by rossabaker** [typelevel/kind-projector#196]
I'm doing it manually, and that makes me sad.

**Comment by rossabaker** [comment]
Though we're usually just backpublishing tags these days, and doing so is nice because it doesn't create a tsunami of Scala Stewards.

`sbt ++${scala.version} clean test publishSigned sonatypeReleaseAll`

**Comment by SethTisue** [comment]
background: https://github.com/sbt/sbt-ci-release/issues/102

**Comment by armanbilge** [comment]
We can possibly close as of https://github.com/typelevel/kind-projector/pull/206.
