### ISSUE TITLE
Missing 0.13.2 release in Maven Central

### ISSUE THREAD

**Issue by aaabramov** [typelevel/kind-projector#198]
The latest release version is 0.13.2 according to https://github.com/typelevel/kind-projector/releases/tag/v0.13.2
But it is missing in Maven Central https://mvnrepository.com/artifact/org.typelevel/kind-projector_2.12.14/0.13.2

Which causes:

```
sbt.librarymanagement.ResolveException: Error downloading org.typelevel:kind-projector_2.12.14:0.13.2
```

I see that there are no changes since 0.13.1 but still could be confusing while upgrading.

**Comment by rossabaker** [comment]
The tag that shouldn't have been for the release that never was!  I didn't publish it, but I'll try republishing now.

**Comment by rossabaker** [comment]
On its way to Maven Central.  If it's still missing in an hour, please reopen.
