### ISSUE TITLE
Add means to specify name of the type parameter

### ISSUE THREAD

**Issue by paulp** [typelevel/kind-projector#38]
Experience shows that while nine times out of ten you can get away with not being to refer to the name of the type parameter, on the tenth time you need it. Usually the cause is a situation where you are forced by scala inference to specify a type parameter, and the type `A` with its unknown name also must be given, because scala offers no way to specify one type argument without specifying them all.

**Comment by TomasMikula** [comment]
See #54. The examples in `polyval.scala` show several examples of natural transformations referring to the type parameter.

**Comment by SethTisue** [comment]
I think at this point we should probably just close this as not-gonna-happen in Scala 2. In Scala 3 a possible future is https://dotty.epfl.ch/docs/reference/other-new-features/named-typeargs.html

**Comment by SethTisue** [comment]
Come to think of it, the repo readme here already outright says "No new features are developed"
