### ISSUE TITLE
Bring Kind-projector to LBS and TLS compilers.

### ISSUE THREAD

**Issue by raulraja** [typelevel/kind-projector#43]
kind-projector has become the de facto standard way to represent type projections in most scala code bases specially those that rely on heavy use of Higher Kinds.

Searching on GitHub yields multiple well known Scala projects that use kind-projector and the amount of success cases show it's a reliable syntax for cases where partial application of higher kinded types is necessary.

The current alternative to not using kind-projector is to use type lambdas, which is an advanced language feature that introduces a lot of noise and complexity specially for newcomers and companies adopting FP in Scala.

I believe type lambdas represent a barrier for extending FP in Scala and Kind projector provides an alternative that is sane and easier to reason about with a syntax that does not deviate from what you'd expect from Scala.

Therefore I propose we consider including kind-projector as valid syntax in Scala.

If this sound reasonable to folks interested and affected by this feature we may consider an approach that may look like:

1. A SIP and PR to LBS and TLS.

2. Enabling this syntax for early adopters in the Typelevel Scala compiler fork and following a similar approach as @milessabin did for SI-2712.
As in SI-2712 those using the Typelevel compiler can enable the fix via compiler flags not requiring the compiler plugin as a dependency.

This issue is here to start the discussion to see if there is interest and what it will take to do so along with any potential issues that may arise from this language change.

A few links for reference :

[Twitter conversation where this started](https://twitter.com/raulraja/status/797955279199539200?s=09)

@retronym pointed out also the existing work that @non and @puffnfresh did here https://github.com/typelevel/scala/pull/73

Tagging folks that may be interested in this issue: @non @milessabin @retronym @adriaanm

Thanks!

**Comment by non** [comment]
So here's a quick overview of some questions that I think need to be answered by a SIP:

1. Are we committed to representing type lambdas with the projection encoding (e.g. `({type L[x] = (x, x)})#L`)? Or are we going to add a new AST node such as `TypeFunction` above? There are known issues with projection, but on the other hand adding a new node will require a lot more design work and testing.

2. Are we committed to the encoding of function syntax (e.g. `Lambda[`+a` => F[a]]`)? In the Typelevel fork I think we wrote this as `[+a] => F[a]` -- is it worth it to change the parser? The former reserves some new names but is currently used in codebases. The latter is closer to what the Scala compiler currently emits (and terser) but is a new syntax.

3. Are we committed to the encoding of wildcard syntax (e.g. `Either[Int, ?]`)? This seems like the best we can do, even in a SIP, but it does reserve an additional name (that may be used in some other codebases).

**Comment by non** [comment]
Continuing from above, there are basically two independent things we should consider:

 * Keep or change the syntax?
 * Keep or change the encoding?

Here's how I'd characterize the four options:

1. **First-class type functions** This would be a break with *kind-projector*, introducing new AST nodes and terser type function syntax. This is nice for the language but puts stress on the existing community.

2. **Reify status quo** This would involve moving the *kind-projector* phase into the compiler. It provides complete continuity to the community, but is maybe a bit ugly for the language.

3. **Improved encoding** This would involve keeping the existing *kind-projector* syntax, but improving the AST encoding of type functions. This still provides continuity for the community.

4. **Improved syntax** This involves changing the syntax but not the encoding. This puts a burden on the community, keeps the look of the language clean, but has the same problems with using type projection to encode type functions.

**Comment by non** [comment]
One final note -- if we did change the syntax of type functions I think it would be important to back-port the feature to 2.10 and 2.11. Otherwise most projects will continue using *kind-projector* until support for those versions of Scala is completely dropped.

Since *kind-projector* supports 2.10 and 2.11 it would be relatively easy to support those versions using the projection encoding (changing the parser for 2.10 - 2.12 is doable). Adding the AST node to all three versions may also be possible, but could be more work (I'm not sure).

**Comment by sellout** [comment]
My concern would be if it somehow gets in the way of _continued_ kind-projector development. If extensions to it could still be done in a compiler plugin, or if its development within TLS could be as fluid, then great. Just worry about tying things to the release cycle of the compiler, and possibly requiring extra overhead (like more SIPs) going forward.

**Comment by non** [comment]
@sellout I think moving type lambdas into the compiler would slow development on type lambdas. But I don't think it would necessarily slow down other things, such as @paulp's support for polymorphic lambda values.

Are there features related to expressing type lambdas that we still need?

**Comment by andyscott** [comment]
Is there a partial approach where some aspects of this could be moved into the compiler in a manner that wouldn't interfere greatly with continued development on type lambdas?

**Comment by sellout** [comment]
@non polymorphic lambdas was exactly what I was thinking of – I don’t know of any type level features that may be needed.

**Comment by non** [comment]
@sellout I think having the plugin detect built-in support (or not) and just provide whatever was absent could work, assuming we keep the existing syntax. We need to hear from the compiler team -- if they don't like the existing kind-projector syntax then we may have to move to something else.

**Comment by tpolecat** [comment]
I'm kind of torn here. I think the plugin is a great 95% solution but I expect 100% from a language feature, and I don't expect to ever get that last 5% if we just drop it in (2 above). So I guess I would prefer to see it done "right" (1 above) or remain as a plugin.

I'm also unsure that the engineering effort is really worth it. We'll have to put it behind a flag, nd the ability to turn it on via `scalacOptions` instead of `addCompilerPlugin` isn't much of a value-add for me.

**Comment by non** [comment]
@tpolecat Yeah, I'm a bit torn too. However, I think it would be possible to have the plugin compile existing code into the "new scheme" when needed, so we could sort of transition code from a backwards-compatible syntax to a newer syntax.

I agree it would be a bit of work.

**Comment by SethTisue** [comment]
The plugin is fine for Scala 2. Making it a language feature has now happened in Scala 3.
