### ISSUE TITLE
Higher order type lambdas

### ISSUE THREAD

**Issue by Krever** [typelevel/kind-projector#49]
Hi,

is it possible to encode higher order type lambdas like `λ[A => B => A]` or `λ[A => λ[B => A]]` ?

I tried but end up with `not found: type B` and `not found: type λ`.

Thanks

**Comment by non** [comment]
@Krever Sorry I didn't see this earlier.

Scala doesn't support this kind of "type currying" in a useful way. It's something that others have wanted (in particular I think @mandubian experimented with this), but requires more than a syntactic change to Scala.
