### ISSUE TITLE
Implement a Scalafix rewrite

### ISSUE THREAD

**Issue by dwijnand** [typelevel/kind-projector#86]
I think it would be useful to implement a Scalafix rewrite that rewrote code to use the improved syntax kind-projector provides.

**Comment by SethTisue** [comment]
pretty skeptical it would be worth it, since the type-lambda technique isn't obvious at all, and nobody promotes that technique anymore, they promote this plugin, which has existed since 2012

**Comment by dwijnand** [comment]
Sure, it's niche and shrinking how many trees this would reach.
